=== Vladimir563/VLADFOM.ITMO.HTML_XML/VLADFOM.ITMO.HTML.JSON.XML/lessons_XML.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="modules">
    <xs:complexType>
      <xs:sequence>
        <xs:element name ="module" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="teacher" type="xs:string"/>
              <xs:element name="begin" type="xs:date"/>
              <xs:element name="end" type="xs:date"/>
              <xs:element name="source" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Vladimir563/VLADFOM.ITMO.HTML_XML/VLADFOM.ITMO.HTML.JSON.XML/lessons-ns.xml
<?xml version = "1.0" encoding ="utf-8"?>
<modules xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lessons_XML.xsd">
  <module>
    <title>ProgrammingTechnologies</title>
    <teacher>Osipov</teacher>
    <begin>2020-09-29</begin>
    <end>2020-10-16</end>
    <source>Software application development (руководство по разработке программного обеспечения)</source>
  </module>
  <module>
    <title>Introduction in databases</title>
    <teacher>Osetrova</teacher>
    <begin>2020-11-09</begin>
    <end>2020-11-20</end>
    <source>SQL server basics</source>
  </module>
  <module>
    <title>Windows application development on the C# platform</title>
    <teacher>Smolyaninov</teacher>
    <begin>2020-11-23</begin>
    <end>2020-12-11</end>
    <source>Основы Windows Presentation Foundation</source>
  </module>
  <module>
    <title>Markable technology essential course</title>
    <teacher>Smolyaninov</teacher>
    <begin>2020-12-14</begin>
    <end>2020-12-18</end>
    <source>XML. Базовый курс</source>
  </module>
</modules>

<!-- Создайте XML-документ, в котором самостоятельно опишите план (расписание) 
дисциплин процесса Вашего обучения (например, название предмета, фамилию преподавателя, 
время занятий, даты начала и окончания курсов и т.п.).-->
